### ISSUE TITLE
Issues on new update Nov 27 2020

### ISSUE THREAD

**Issue by manyaqx** [icescentral/COVID19-Lab-Results#1]
Hi there,

I just want you to let you know there are few errors..

1) COVID19_processing.py
   

-  Output file name has an issue. In line 22 you already define the file name as "'Olis_output_' + CURDATE + '.csv'".. On the otherhand, you add another '.csv' at line 1051..

 
PS> LINE NUMBERS CAN BE DIFFERENT in your system

2) COVID19_rollup.py
   

- If you dont fix the first error, you will get the error when you run this script..

- Second issue is 'OBSERVATIONDATETIME_TR' columns is not found when try to merge the df at line 523. The problem is OBSERVATIONDATETIME_TR comes from testrequestscol dataframe and named 'observationdatetime' column. This 'observationdatetime' column comes from df_clean dataframe at line 312.   The problem is you drop this column at line 312. Thats why this column cannot found.

df_clean.drop(['observationresultstatus','exclude_flag','observationcode','obersvationdatetime'], 1, inplace=True)

Regards
Firat Yilmaz

**Comment by BranCh7** [comment]
Hi Firat,

Thanks for flagging these issues. Apologies, I didn't see this post until now. I changed the filename parameters to not include the file extension since I am using to_csv and the file extension is fixed.

I am not sure I understand the second issue; observationdatetime is not used in the script after it is dropped. The only merges are on observationdate, which is a separate variable with date precision.

Thanks,
Branson

**Comment by manyaqx** [comment]
Hi Branson,

Thank you for reply… I develop my own script the automate the update process. When you release the new update, my script automatically connects to github and update our code automatically. I don’t really check that what is the new changes. We still keep that field “OBSERBATIONDATETIME_TR” for testing purposes. I want to warn you that may be other peoples are using that field and may face same issue.

Regards
